# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c9cd9fa50519b73bcb21435e2ac56bc90bfc1edee72b8b9505a3af45faaaf856a7d03e204c0ba578b0773ca0c51a6f4978aef9f3d6c021b6005e1d24ed00cae

test:
  secret_key_base: 737e6d5c77fa16c518afb2907175f43e80a2026fd14067078b41e91d13cdca9776e374da4d602f538efdbcec1f9296349dfa22535ba23ea8ab1bb1ddbf98c4ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
